name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file ci/Dockerfile --tag stylechecker:$(date +%s)
    - name: Code style check
      run: docker run stylechecker:$(data +%s) black --check stylechecker.py
