name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file ci/Dockerfile --tag stylechecker:latest
    - name: Code style check
      run: docker run -v $PWD:/stylechecker stylechecker:latest black --check /stylechecker/
    - name: Unit tests
      run: docker run -v $PWD:/stylechecker stylechecker:latest coverage run -m unittest test.test_stylechecker
    - name: Coverage report
      run: docker run -v $PWD:/stylechecker stylechecker:latest coverage report -m
    - name: Check latex version
      run: apt list --installed | grep texlive
    - name: Integration test
      run: docker run -v $PWD:/stylechecker stylechecker:latest python3 -m unittest ci.integration_test
